### ISSUE TITLE
Allure generate not working on azure

### ISSUE THREAD

**Issue by andrematosfundao** [allure-framework/allure-vsts#1]
Hello I installed the allure addon for azure and cannot get it working. 

I followed instruction in 
https://marketplace.visualstudio.com/items?itemName=Molecula.allure-test-reports&ssr=false#overview
bug get this error when it tries to generate the report.

![image](https://user-images.githubusercontent.com/33062016/215706361-0c51abab-dc8d-4be4-930c-2c84493f629e.png)

    C:\Program Files\nodejs\node.exe D:\a\_tasks\AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb\1.0.0\node_modules\allure-commandline\bin\allure generate --output D:\a\1\s\allure-report\20230130.3 D:\a\1\s\AzureTest\AzureTest\bin\Release\net7.0\allure-results
    Command aborted due to exception {}.
    org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	    at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	    at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	    at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
    Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
	    at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
	    at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	    at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
    org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	    at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	    at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	    at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)

I guess this is because the default allure in this task is 6 years old and my test code uses the latest allure-result 3.5.0.73

on my own azure agent i installed latest allure command line but then I get different error:
![image](https://user-images.githubusercontent.com/33062016/215708084-47a8d93a-d2f3-4862-84c4-c7216d59853e.png)

It has been a while since this task is updated, my guess is that this just needs some updates to the latest version.

can anyone help?

**Comment by andrematosfundao** [comment]
@just-boris can you have a look at this?
